name: Snyk Security Scan

on:
  push:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: portfolio-website/src

      - name: Run Snyk Security Scan
        uses: snyk/actions/node@master
        with:
          args: --file=src/package.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
